apiVersion: v1
kind: Secret
metadata:
  name: supabase-secret
type: Opaque
stringData:
  SUPABASE_URL: "REPLACE_WITH_YOUR_SUPABASE_URL"
  SUPABASE_KEY: "REPLACE_WITH_YOUR_SUPABASE_SERVICE_ROLE_KEY"
