apiVersion: v1
kind: Secret
metadata:
  name: supabase-secret
type: Opaque
stringData:
  SUPABASE_URL: "https://ecycgdubgadbfsceglnn.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeWNnZHViZ2FkYmZzY2VnbG5uIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDIwODc0NiwiZXhwIjoyMDc1Nzg0NzQ2fQ.zsYIPHfXCsPlxNE-DQZX5ja14B1q6H7OIX2sAeeGqr4"
